// react-app/src/components/login.js
import React, { useState, useContext } from 'react';
import PropTypes from 'prop-types';


import { Redirect } from 'react-router-dom';
import UserContext from '../context/user';

const LoginPage = props => {

    const [ form, setForm ] = useState({ userName: '', password: '' });
    const [ loading, setLoading ] = useState(false);
    const context = useContext(UserContext);


    const handleChange = name => e => {
        setForm({...form, [name]: e.target.value });
    }

    const handleSubmit = e => {
        e.preventDefault();

        if (!form.userName || !form.password) return;

        setLoading(true);

        setTimeout(() => {
            localStorage.setItem('isAuthed', true);
            localStorage.setItem('userName', form.userName);
            context.login(form.userName, form.password);
            props.history.push('/forum');
        }, 1000);
    }

    if (context.userName) {
        return (
          <Redirect to='/forum' />
        );
    }
  
    return (
        <form className="login-block" onSubmit={ handleSubmit }>
            <h1>Авторизация</h1>
            <label>
                User name
            <input className="form-control" type="text" placeholder="Username" value={ form.userName } onChange={ handleChange('userName') } required />
            </label>
            <label>
                Password
            <input className="form-control" type="password" placeholder="Password" value={ form.password } onChange={ handleChange('password') } required />
            </label>
            <button className="btn" disabled={ loading }>
                Войти
            </button>
        </form >
    )
}

LoginPage.propTypes = {
    history: PropTypes.object.isRequired
}

export default LoginPage

// front-end/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from "@angular/router";
import { FormGroup, FormBuilder, Validators } from "@angular/forms";
import { UtilsService } from '../utils.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {

  loginForm: FormGroup;
  loading = false;
  error: string = null;

  constructor(
    private formBuilder: FormBuilder,
    private router: Router,
    private utils: UtilsService,
  ) { }

  ngOnInit() {
    this.loginForm = this.formBuilder.group({
      username: ["", Validators.required],
      password: ["", Validators.required]
    });
  }

  get username() { 
    return this.loginForm.get('username'); 
  }

  get password() { 
    return this.loginForm.get('password'); 
  }

  login() {

    this.utils.setAsTouched(this.loginForm);

    if (this.loginForm.invalid) {
      return;
    }
    
    this.loading = true;
    
    setTimeout(() => {
      this.loading = false;
      localStorage.setItem('isAuth', "true");
      localStorage.setItem('login', this.username.value);
      this.router.navigate(["/forum"]);
    }, 1000);
  }


}

<form class="login-block" [formGroup]="loginForm" (ngSubmit)="login()">
    <h1>Авторизация</h1>
    <label>
      User name
      <input class="form-control" type="text" placeholder="Username" formControlName="username" name="username" required/>
    </label>
    <label>
      Password
      <input class="form-control" type="password" placeholder="Password" formControlName="password" name="password" required/>
    </label>
    <button class="btn" [disabled]="loading">
      Войти
    </button>
</form>
